
name: API testing flows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 00 7 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -DSuite=Suite -X

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with: 
       name: Logs
       path: logs/
